<html>
<head>
    <?php $stats = $block->getStatistics();
    foreach ($stats as $item) {
        var_dump($item->stats['0']->metrics);
    }
    ?>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {'packages':['line']});
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {

            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Day');
            data.addColumn('number', 'Guardians of the Galaxy');
            data.addColumn('number', 'The Avengers');
            data.addColumn('number', 'Transformers: Age of Extinction');
            data.addRows([
                ["2020-3-15",  1, 80.8, 41.8],
                ["2020-3-16",  0, 80.8, 41.8],
                ["2020-3-17",  30.9, 69.5, 32.4],
                ["2020-3-18",  25.4,   57, 25.7],
                ["2020-3-19",  11.7, 18.8, 10.5],
                ["2020-3-20",  11.9, 17.6, 10.4],
                ["2020-3-21",   8.8, 13.6,  7.7],
                ["2020-3-22",   7.6, 12.3,  9.6],
                ["2020-3-23",  12.3, 29.2, 10.6],
                ["2020-3-24",  16.9, 42.9, 14.8],
                ["2020-3-25", 12.8, 30.9, 11.6],
                ["2020-3-26",  5.3,  7.9,  4.7],
                ["2020-3-27",  6.6,  8.4,  5.2],
                ["2020-3-28",  4.8,  6.3,  3.6],
                ["2020-3-29",  4.2,  6.2,  3.4]
            ]);

            var options = {
                chart: {
                    title: 'Box Office Earnings in First Two Weeks of Opening',
                    subtitle: 'in millions of dollars (USD)'
                },
                width: 1600,
                height: 700,
                axes: {
                    x: {
                        0: {side: 'bottom'}
                    }
                }
            };

            var chart = new google.charts.Line(document.getElementById('statistics'));

            chart.draw(data, google.charts.Line.convertOptions(options));
        }
    </script>
</head>
<body>
<div id="statistics"></div>
</body>
</html>
