<html>
<?php
$helper = $this->helper("Lof\SendGrid\Helper\Data");
$api_key = $helper->getSendGridConfig('general', 'api_key');
?>
<head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {'packages':['line']});
        google.charts.setOnLoadCallback(drawChart);
        function getResponse(callback) {
            require(['jquery', 'jquery/ui'], function($){
                $('#btn-apply').on("click", function() {
                    var start = $('#start').val();
                    var end = $('#end').val();
                    var settings = {
                        "async": true,
                        "crossDomain": true,
                        "url": "https://api.sendgrid.com/v3/stats?start_date="+start+"&end_date="+end+"&aggregated_by=day",
                        "method": "GET",
                        "headers": {
                            "authorization": "Bearer <?= $api_key?>"
                        },
                        "data": "{}"
                    }
                    $.ajax(settings).done(function (response) {
                        callback(response);
                    });
                });
            });
        }
        function drawChart() {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Day');
            data.addColumn('number', 'Blocks');
            data.addColumn('number', 'Bounce Drop');
            data.addColumn('number', 'Bounces');
            data.addColumn('number', 'Clicks');
            data.addColumn('number', 'Deferred');
            data.addColumn('number', 'Delivered');
            data.addColumn('number', 'Invalid Emails');
            data.addColumn('number', 'Opens');
            data.addColumn('number', 'Processed');
            data.addColumn('number', 'Requests');
            data.addColumn('number', 'Spam Report Drops');
            data.addColumn('number', 'Spam Report');
            data.addColumn('number', 'Unique Clicks');
            data.addColumn('number', 'Unique Opens');
            data.addColumn('number', 'Unsubscribe Drops');
            data.addColumn('number', 'Unsubscribes');
            getResponse(function(response) {
                response.forEach(myFunction);
                function myFunction(item) {
                    data.addRows([
                        [
                            item.date,
                            item.stats['0'].metrics.blocks,
                            item.stats['0'].metrics.bounce_drops,
                            item.stats['0'].metrics.bounces,
                            item.stats['0'].metrics.clicks,
                            item.stats['0'].metrics.deferred,
                            item.stats['0'].metrics.delivered,
                            item.stats['0'].metrics.invalid_emails,
                            item.stats['0'].metrics.opens,
                            item.stats['0'].metrics.processed,
                            item.stats['0'].metrics.requests,
                            item.stats['0'].metrics.spam_report_drops,
                            item.stats['0'].metrics.spam_reports,
                            item.stats['0'].metrics.unique_clicks,
                            item.stats['0'].metrics.unique_opens,
                            item.stats['0'].metrics.unsubscribe_drops,
                            item.stats['0'].metrics.unsubscribes
                        ],
                    ]);
                }
                var options = {
                    chart: {
                        title: 'SendGrid Statistics',
                        subtitle: '(times)'
                    },
                    width: 1600,
                    height: 700,
                    axes: {
                        x: {
                            0: {side: 'bottom'}
                        }
                    }
                };
                var chart = new google.charts.Line(document.getElementById('statistics'));
                chart.draw(data, google.charts.Line.convertOptions(options));
            })
        }
    </script>
</head>
<body>
<label for="start">Start date:</label>
<input type="date" id="start" name="trip-start"
       value = "<?= $block->getTimeNow() ?>"
       min="2020-01-01" max="<?= $block->getTimeNow() ?>">
<label for="start">End date:</label>
<input type="date" id="end" name="trip-end"
       value="<?= $block->getTimeNow() ?>"
       min="2020-01-01" max="<?= $block->getTimeNow() ?>">
<button id="btn-apply">Apply</button>
<div id="statistics"></div>
</body>
</html>
